// export const ADD_SUBSCRIBER ='ADD_SUBSCRIBER' ;
// export const REMOVE_SUBSCRIBER ='REMOVE_SUBSCRIBER';  // IN ORDER TO USE IT OUTSIDE

export const FETCH_ALL_EMPLOYEES ='FETCH_ALL_EMPLOYEES';  // IN ORDER TO USE IT OUTSIDE
export const FETCH_ALL_TASKS ='FETCH_ALL_TASKS';  // IN ORDER TO USE IT OUTSIDE
export const DELETE_TASKS ='DELETE_TASKS';  // IN ORDER TO USE IT OUTSIDE
export const ADD_EMPLOYEES='ADD_EMPLOYEES';  // IN ORDER TO USE IT OUTSIDE
